---
title: "ESM262-Assignment1-Vela"
author: "Alejandro Vela"
date: "5/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Part 1: Import and Tidy

## Part 1-1: Load Libraries


```{r load_libraries}

library(tidyverse)
library(readr)
library(tibble)
library(dplyr)
library(tidyr)

```
## Part 1-2: Import Raw Data

```{r Import_Data}


Raw_CA_Gazetteer_Dataset <- read_delim("~/Documents/Bren School Documents/3-Spring Quarter 2018/ESM262-Computing for Environmental Sciences/Assignment1/CA_Features_20180401.txt", 
    "|", escape_double = FALSE, trim_ws = TRUE)

View(Raw_CA_Gazetteer_Dataset)

```

## Part 1-3: Copy Only Required Columns

```{r Select_Columns}

CA_Gazetteer_NewColumns <- Raw_CA_Gazetteer_Dataset

names(CA_Gazetteer_NewColumns) <- c("ID", "Name", "Class", "State", "State_ID", "County", "County_ID", "Latitude_DMS", "Longitude_DMS", "Latitude_DEC", "Longitude_DEC", "Latitude_DMS_SRC", "Longitude_DMS_SRC", "Latitude_DEC_SRC", "Longitude_DEC_SRC", "Elevation_MTS", "Elevation_FT", "MapName", "DateCreated", "DateEdited")

View(CA_Gazetteer_NewColumns)

CA_Gazetter_SelectedColumns <- select(CA_Gazetteer_NewColumns, ID, Name, Class, State, County, Latitude_DEC, Longitude_DEC, Latitude_DEC_SRC, Longitude_DEC_SRC, Elevation_MTS, MapName, DateCreated, DateEdited)

View(CA_Gazetter_SelectedColumns)
```

## Part 1-4: Extract California and Delete Unknown Primary Latitude or Longitude

```{r Extract_CA_DeleteUnknowns}

CA_Gazetteer_CAOnly <- CA_Gazetter_SelectedColumns %>%
  filter(State == "CA") %>%
  filter(Latitude_DEC != "") %>%
  filter(Longitude_DEC != "")

View(CA_Gazetteer_CAOnly)

```

## Part 1-5: Write the Gaz Tibble to a CVS file (Using "|" as a delimiter)

```{r Extract_CA_DeleteUnknowns}

write.table(CA_Gazetteer_CAOnly, file = "Gazetteer_CAOnly.txt", sep = "|",
            row.names = TRUE, col.names = NA)

```
